//! `pv_transpiler` -- lexer, LALRPOP grammar, and AST for the PlainVulkan
//! (`.pv`) scripting language.
//!
//! The public entry point is [`parse`], which turns source text into a
//! [`ast::Program`] or a list of human-readable [`diagnostics::Diagnostic`]s.

pub mod ast;
mod ast_helpers;
pub mod diagnostics;
pub mod lexer;
pub mod token;

// Generated by build.rs (lalrpop) from src/pv.lalrpop.
use lalrpop_util::lalrpop_mod;
lalrpop_mod!(
    #[allow(clippy::all)]
    #[allow(unused)]
    pv
);

use diagnostics::Diagnostic;
use lexer::Lexer;

/// Parse a complete PlainVulkan source file into an AST.
pub fn parse(src: &str) -> Result<ast::Program, Vec<Diagnostic>> {
    let lexer = Lexer::new(src);
    let parser = pv::ProgramParser::new();
    parser
        .parse(lexer)
        .map_err(|e| vec![diagnostics::from_parse_error(e)])
}

/// Parse a single expression (handy for tests, REPL-style tools, etc).
pub fn parse_expr(src: &str) -> Result<ast::Expr, Vec<Diagnostic>> {
    let lexer = Lexer::new(src);
    let parser = pv::ExprParser::new();
    parser
        .parse(lexer)
        .map_err(|e| vec![diagnostics::from_parse_error(e)])
}

/// Render a file's diagnostics as a single human-readable string.
pub fn render_diagnostics(filename: &str, src: &str, diags: &[Diagnostic]) -> String {
    diags
        .iter()
        .map(|d| d.render(filename, src))
        .collect::<Vec<_>>()
        .join("\n")
}
