//! AST -> C++ code generation.
//!
//! Design summary (see runtime/README.md for the full rationale):
//! - PlainVulkan has no type annotations anywhere in its grammar, so every
//!   `.pv` variable/parameter/return value compiles to the single dynamic
//!   `pv::Value` type (runtime/include/pv/pv_value.h).
//! - `Pv::Foo(args)` -> `pv::rt::Foo(args)`, validated against
//!   `pv_commands::PV_COMMANDS` first so a wrong argument count is a clean
//!   `pvcc` diagnostic rather than a C++ overload-resolution error.
//! - Every user identifier is emitted with a `u_` prefix, so a `.pv`
//!   variable can never collide with a C++ keyword, a standard-library
//!   name, or one of this file's own generated helper names (`__lv`,
//!   `main`, ...) -- there's no reserved-word table to maintain.
//! - `a[i] = v` / `a.b = v` compile through `pv::index_ref` / `pv::
//!   member_ref`, which auto-vivify and return `Value&`, so arbitrarily
//!   chained targets (`a.b[0].c = v`) become one chained C++ expression.
//! - Top-level statements become the body of `int main()`; top-level
//!   `function`s become real C++ functions (forward-declared first, so
//!   mutual recursion works); a `function` nested inside a block becomes a
//!   local `std::function` lambda capturing its enclosing scope by
//!   reference (which also gives it recursion, since the lambda can refer
//!   to its own name inside its body).

use pv_transpiler::ast::*;
use std::collections::HashSet;
use std::fmt::Write as _;

use crate::pv_commands;

#[derive(Debug, Clone)]
pub struct CodegenDiagnostic {
    pub message: String,
    pub span: Option<Span>,
}

pub struct CodegenOutput {
    pub cpp: String,
    pub warnings: Vec<CodegenDiagnostic>,
}

/// The engine commands whose parameter is a C++ *function pointer*
/// (`NetCallback` / `NetCallback1` in pv_runtime.h) rather than the uniform
/// `Value` every other command takes. Their argument therefore has to be the
/// name of a top-level `function` with the matching parameter count -- a
/// literal, a variable, or a nested function (which compiles to a
/// `std::function`, not a raw function pointer) cannot convert. Checking
/// that here turns what would otherwise be an opaque C++ overload error in
/// generated code into a precise .pv diagnostic.
const CALLBACK_COMMANDS: &[(&str, usize)] = &[
    ("OnConnect", 0),
    ("OnDisconnect", 1),
    ("OnReceive", 1),
    ("OnNetworkError", 1),
];

fn callback_arity(name: &str) -> Option<usize> {
    CALLBACK_COMMANDS.iter().find(|(n, _)| *n == name).map(|(_, a)| *a)
}

pub fn generate(program: &Program) -> Result<CodegenOutput, Vec<CodegenDiagnostic>> {
    // Collect top-level function names/arities up front: both the callback
    // check above and the "function used as a value" check in emit_expr need
    // to know them regardless of where they sit relative to the use site.
    let mut top_level_fns = std::collections::HashMap::new();
    for stmt in &program.stmts {
        if let Stmt::Function(f) = stmt {
            top_level_fns.insert(f.name.clone(), f.params.len());
        }
    }
    let mut cg = Codegen {
        errors: Vec::new(),
        warnings: Vec::new(),
        const_scopes: vec![HashSet::new()],
        top_level_fns,
        in_main: false,
    };
    let cpp = cg.emit_program(program);
    if cg.errors.is_empty() {
        Ok(CodegenOutput { cpp, warnings: cg.warnings })
    } else {
        Err(cg.errors)
    }
}

struct Codegen {
    errors: Vec<CodegenDiagnostic>,
    warnings: Vec<CodegenDiagnostic>,
    /// Stack of lexical scopes tracking which names were declared `const`,
    /// innermost last. Used only for the "assignment to const" diagnostic.
    const_scopes: Vec<HashSet<String>>,
    /// Top-level `function` name -> parameter count. Used to validate
    /// callback arguments and to reject using a function as a plain value.
    top_level_fns: std::collections::HashMap<String, usize>,
    /// True while emitting statements that land directly in `int main()`.
    /// `return` is legal in a .pv script's top level, but main() returns
    /// `int`, not `Value`, so those returns need different code than the
    /// ones inside a `function` body.
    in_main: bool,
}

const PREAMBLE: &str = "\
// Auto-generated by pvcc from a PlainVulkan (.pv) source file.
// Do not edit by hand -- re-run `pv build` / `pvcc build` instead.
#include <functional>
#include <cmath>
#include <exception>
#include <string>
#include \"pv/pv_value.h\"
#include \"pv/pv_runtime.h\"

using pv::Value;
";

fn indent(level: usize) -> String {
    "    ".repeat(level)
}

/// Every user-level identifier (variables, parameters, function names) is
/// emitted with this prefix, unconditionally. That -- not a reserved-word
/// table -- is what guarantees a `.pv` name can never collide with a C++
/// keyword, a stdlib symbol, or an internal codegen helper name.
fn sanitize_ident(name: &str) -> String {
    format!("u_{}", name)
}

fn cpp_string_literal(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            '\0' => out.push_str("\\0"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn cpp_float_literal(f: f64) -> String {
    if f.is_nan() {
        return "std::nan(\"\")".to_string();
    }
    if f.is_infinite() {
        return if f > 0.0 { "HUGE_VAL".to_string() } else { "(-HUGE_VAL)".to_string() };
    }
    let mut s = format!("{}", f);
    if !s.contains('.') && !s.contains('e') && !s.contains('E') {
        s.push_str(".0");
    }
    s
}

impl Codegen {
    fn emit_program(&mut self, program: &Program) -> String {
        let mut out = String::new();
        out.push_str(PREAMBLE);
        out.push('\n');

        // Top-level `var`/`let`/`const` declarations are meant to be
        // script-wide globals (any function can see and use them -- this
        // is the whole point of declaring state like `var score = 0;`
        // outside of any function), but a naive translation would make
        // them C++ locals of `main()`, invisible to sibling functions.
        // So: emit each one as a real file-scope `Value` global (default-
        // initialized to null, order-independent since Value's default
        // constructor has no dependencies), and turn its *initializer*
        // into a plain assignment at its original position inside
        // `main()` -- that keeps initialization order (and any side
        // effects an initializer's expression has, e.g. calling
        // `Pv::LoadMesh` after `Pv::Init()`) exactly matching the
        // script's top-to-bottom execution order, which hoisting the
        // initializer itself into the global's static-init would break.
        for stmt in &program.stmts {
            if let Stmt::VarDecl(d) = stmt {
                let _ = writeln!(out, "Value {} = Value();", sanitize_ident(&d.name));
                // Registered here (not when the initializer assignment is
                // emitted below) so const-ness is known to every function
                // body regardless of where the declaration sits in the
                // source relative to that function.
                self.declare(&d.name, d.kind == DeclKind::Const);
            }
        }
        out.push('\n');

        // Forward-declare every top-level function first so call order in
        // the source (including mutual recursion) never matters.
        for stmt in &program.stmts {
            if let Stmt::Function(f) = stmt {
                let params = f
                    .params
                    .iter()
                    .map(|_| "Value".to_string())
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(out, "Value {}({});", sanitize_ident(&f.name), params);
                self.const_scopes[0].remove(&f.name); // functions are callable, not const-checked
            }
        }
        out.push('\n');

        let mut main_stmts: Vec<&Stmt> = Vec::new();
        for stmt in &program.stmts {
            match stmt {
                Stmt::Function(f) => {
                    self.emit_top_level_function(&mut out, f);
                    out.push('\n');
                }
                other => main_stmts.push(other),
            }
        }

        out.push_str("int main(int argc, char** argv) {\n");
        out.push_str("    (void)argc; (void)argv;\n");
        // The whole script body runs inside a try block. Without it, any
        // exception escaping a runtime call (std::bad_alloc from an absurd
        // array index, a filesystem error deep in an asset loader, ...)
        // reaches std::terminate and the game dies with a bare "Abort" and
        // no diagnostic -- the single worst failure mode for someone
        // debugging their own .pv script. Logging it and exiting non-zero
        // costs nothing and always says what happened.
        out.push_str("    try {\n");
        self.in_main = true;
        for stmt in main_stmts {
            if let Stmt::VarDecl(d) = stmt {
                // The global was already declared (and registered for
                // const-checking) above; here we just run its initializer
                // (if any) at the right point in program order, as a
                // plain assignment rather than a declaration.
                if let Some(init) = &d.init {
                    let init_cpp = self.emit_expr(init);
                    let _ = writeln!(out, "        {} = {};", sanitize_ident(&d.name), init_cpp);
                }
                continue;
            }
            self.emit_stmt(&mut out, stmt, 2, 0);
        }
        self.in_main = false;
        out.push_str("        return 0;\n");
        out.push_str("    } catch (const std::exception& e) {\n");
        out.push_str("        pv::rt::LogError(Value(std::string(\"unhandled runtime error: \") + e.what()));\n");
        out.push_str("        return 1;\n");
        out.push_str("    } catch (...) {\n");
        out.push_str("        pv::rt::LogError(Value(std::string(\"unhandled runtime error (unknown exception type)\")));\n");
        out.push_str("        return 1;\n");
        out.push_str("    }\n");
        out.push_str("}\n");

        out
    }

    fn emit_top_level_function(&mut self, out: &mut String, f: &FunctionDecl) {
        let params = f
            .params
            .iter()
            .map(|p| format!("Value {}", sanitize_ident(p)))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "Value {}({}) {{", sanitize_ident(&f.name), params);
        self.push_scope();
        for p in &f.params {
            self.const_scopes.last_mut().unwrap().remove(p);
        }
        for stmt in &f.body.stmts {
            self.emit_stmt(out, stmt, 1, 0);
        }
        self.pop_scope();
        out.push_str("    return Value();\n");
        out.push_str("}\n");
    }

    fn push_scope(&mut self) {
        self.const_scopes.push(HashSet::new());
    }
    fn pop_scope(&mut self) {
        self.const_scopes.pop();
    }
    fn declare(&mut self, name: &str, is_const: bool) {
        // A fresh declaration shadows any outer const-ness for this name
        // within the current scope.
        if is_const {
            self.const_scopes.last_mut().unwrap().insert(name.to_string());
        } else {
            self.const_scopes.last_mut().unwrap().remove(name);
        }
    }
    fn is_const(&self, name: &str) -> bool {
        self.const_scopes.iter().rev().any(|s| s.contains(name))
    }

    fn root_ident<'a>(&self, lv: &'a LValue) -> &'a str {
        match lv {
            LValue::Ident(n, _) => n,
            LValue::Index(base, _, _) => self.root_ident(base),
            LValue::Member(base, _, _) => self.root_ident(base),
        }
    }

    fn emit_stmt(&mut self, out: &mut String, stmt: &Stmt, ind: usize, loop_depth: usize) {
        let pad = indent(ind);
        match stmt {
            Stmt::VarDecl(d) => {
                let init_cpp = d
                    .init
                    .as_ref()
                    .map(|e| self.emit_expr(e))
                    .unwrap_or_else(|| "Value()".to_string());
                let kw = if d.kind == DeclKind::Const { "const Value" } else { "Value" };
                let _ = writeln!(out, "{}{} {} = {};", pad, kw, sanitize_ident(&d.name), init_cpp);
                self.declare(&d.name, d.kind == DeclKind::Const);
            }
            Stmt::Assign(a) => {
                if self.is_const(self.root_ident(&a.target)) {
                    self.errors.push(CodegenDiagnostic {
                        message: format!(
                            "cannot assign to `{}`: it was declared `const`",
                            self.root_ident(&a.target)
                        ),
                        span: Some(a.span),
                    });
                }
                let value_cpp = self.emit_expr(&a.value);
                let expr = self.emit_assign_as_expr(&a.target, a.op, value_cpp);
                let _ = writeln!(out, "{}{};", pad, expr);
            }
            Stmt::Expr(e) => {
                let _ = writeln!(out, "{}{};", pad, self.emit_expr(&e.expr));
            }
            Stmt::If(s) => {
                let _ = writeln!(out, "{}if ((bool)({})) {{", pad, self.emit_expr(&s.cond));
                self.push_scope();
                for st in &s.then_block.stmts {
                    self.emit_stmt(out, st, ind + 1, loop_depth);
                }
                self.pop_scope();
                let _ = writeln!(out, "{}}}", pad);
                for (cond, block) in &s.elifs {
                    let _ = writeln!(out, "{}else if ((bool)({})) {{", pad, self.emit_expr(cond));
                    self.push_scope();
                    for st in &block.stmts {
                        self.emit_stmt(out, st, ind + 1, loop_depth);
                    }
                    self.pop_scope();
                    let _ = writeln!(out, "{}}}", pad);
                }
                if let Some(else_block) = &s.else_block {
                    let _ = writeln!(out, "{}else {{", pad);
                    self.push_scope();
                    for st in &else_block.stmts {
                        self.emit_stmt(out, st, ind + 1, loop_depth);
                    }
                    self.pop_scope();
                    let _ = writeln!(out, "{}}}", pad);
                }
            }
            Stmt::While(s) => {
                let _ = writeln!(out, "{}while ((bool)({})) {{", pad, self.emit_expr(&s.cond));
                self.push_scope();
                for st in &s.body.stmts {
                    self.emit_stmt(out, st, ind + 1, loop_depth + 1);
                }
                self.pop_scope();
                let _ = writeln!(out, "{}}}", pad);
            }
            Stmt::For(s) => {
                self.push_scope();
                let init_cpp = match &s.init {
                    ForInit::VarDecl(d) => {
                        let init_e = d
                            .init
                            .as_ref()
                            .map(|e| self.emit_expr(e))
                            .unwrap_or_else(|| "Value()".to_string());
                        self.declare(&d.name, d.kind == DeclKind::Const);
                        format!("Value {} = {}", sanitize_ident(&d.name), init_e)
                    }
                    ForInit::Assign(a) => {
                        let value_cpp = self.emit_expr(&a.value);
                        self.emit_assign_as_expr(&a.target, a.op, value_cpp)
                    }
                    ForInit::Expr(e) => self.emit_expr(&e.expr),
                    ForInit::Empty => String::new(),
                };
                let cond_cpp = s.cond.as_ref().map(|c| self.emit_expr(c)).unwrap_or_default();
                let update_cpp = match &s.update {
                    ForUpdate::Assign(a) => {
                        let value_cpp = self.emit_expr(&a.value);
                        self.emit_assign_as_expr(&a.target, a.op, value_cpp)
                    }
                    ForUpdate::Expr(e) => self.emit_expr(&e.expr),
                    ForUpdate::Empty => String::new(),
                };
                let _ = writeln!(out, "{}for ({}; {}; {}) {{", pad, init_cpp, cond_cpp, update_cpp);
                for st in &s.body.stmts {
                    self.emit_stmt(out, st, ind + 1, loop_depth + 1);
                }
                let _ = writeln!(out, "{}}}", pad);
                self.pop_scope();
            }
            Stmt::Break(span) => {
                if loop_depth == 0 {
                    self.errors.push(CodegenDiagnostic {
                        message: "`break` used outside of a loop".to_string(),
                        span: Some(*span),
                    });
                }
                let _ = writeln!(out, "{}break;", pad);
            }
            Stmt::Continue(span) => {
                if loop_depth == 0 {
                    self.errors.push(CodegenDiagnostic {
                        message: "`continue` used outside of a loop".to_string(),
                        span: Some(*span),
                    });
                }
                let _ = writeln!(out, "{}continue;", pad);
            }
            Stmt::Return(r) => {
                // A `return` at the script's top level is legal PlainVulkan
                // ("stop the script here"), but it lands in `int main()`,
                // which cannot return a Value -- emitting one produced
                // C++ that simply did not compile. Evaluate the expression
                // (it may have side effects), then use it as the process
                // exit code when it's a number and 0 otherwise, which is
                // what a script author writing `return 1;` means.
                if self.in_main {
                    match &r.value {
                        Some(e) => {
                            let v = self.emit_expr(e);
                            let _ = writeln!(
                                out,
                                "{}{{ Value __ret = {}; return __ret.isNumber() ? \
                                 static_cast<int>(__ret.asInt()) : 0; }}",
                                pad, v
                            );
                        }
                        None => {
                            let _ = writeln!(out, "{}return 0;", pad);
                        }
                    }
                    return;
                }
                let v = r
                    .value
                    .as_ref()
                    .map(|e| self.emit_expr(e))
                    .unwrap_or_else(|| "Value()".to_string());
                let _ = writeln!(out, "{}return {};", pad, v);
            }
            Stmt::Block(b) => {
                let _ = writeln!(out, "{}{{", pad);
                self.push_scope();
                for st in &b.stmts {
                    self.emit_stmt(out, st, ind + 1, loop_depth);
                }
                self.pop_scope();
                let _ = writeln!(out, "{}}}", pad);
            }
            Stmt::Function(f) => {
                // Nested function -> local recursive lambda. `std::function`
                // (rather than `auto`) lets the lambda's own initializer
                // refer to its name for recursion, and `[&]` gives it
                // access to the enclosing scope, same as the surrounding
                // block would see.
                let param_types = f.params.iter().map(|_| "Value").collect::<Vec<_>>().join(", ");
                let params = f
                    .params
                    .iter()
                    .map(|p| format!("Value {}", sanitize_ident(p)))
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(
                    out,
                    "{}std::function<Value({})> {} = [&]({}) -> Value {{",
                    pad,
                    param_types,
                    sanitize_ident(&f.name),
                    params
                );
                self.push_scope();
                for p in &f.params {
                    self.const_scopes.last_mut().unwrap().remove(p);
                }
                // Inside the lambda we are no longer emitting main()'s body,
                // so `return` here is a normal Value-returning return.
                let outer_in_main = self.in_main;
                self.in_main = false;
                for st in &f.body.stmts {
                    self.emit_stmt(out, st, ind + 1, 0);
                }
                self.in_main = outer_in_main;
                self.pop_scope();
                let _ = writeln!(out, "{}    return Value();", pad);
                let _ = writeln!(out, "{}}};", pad);
            }
        }
    }

    fn emit_lvalue_ref(&mut self, lv: &LValue) -> String {
        match lv {
            LValue::Ident(name, _) => sanitize_ident(name),
            LValue::Index(base, idx, _) => {
                format!("pv::index_ref({}, {})", self.emit_lvalue_ref(base), self.emit_expr(idx))
            }
            LValue::Member(base, field, _) => {
                format!("pv::member_ref({}, {})", self.emit_lvalue_ref(base), cpp_string_literal(field))
            }
        }
    }

    fn emit_assign_as_expr(&mut self, target: &LValue, op: AssignOp, value_cpp: String) -> String {
        let target_ref = self.emit_lvalue_ref(target);
        let body = match op {
            AssignOp::Assign => format!("__lv = {};", value_cpp),
            AssignOp::AddAssign => format!("__lv = __lv + ({});", value_cpp),
            AssignOp::SubAssign => format!("__lv = __lv - ({});", value_cpp),
            AssignOp::MulAssign => format!("__lv = __lv * ({});", value_cpp),
            AssignOp::DivAssign => format!("__lv = __lv / ({});", value_cpp),
            AssignOp::ModAssign => format!("__lv = __lv % ({});", value_cpp),
        };
        format!("([&]() -> Value {{ Value& __lv = {}; {} return __lv; }})()", target_ref, body)
    }

    fn emit_expr(&mut self, e: &Expr) -> String {
        match e {
            Expr::IntLiteral(n, _) => format!("Value(static_cast<int64_t>({}))", n),
            Expr::FloatLiteral(f, _) => format!("Value({})", cpp_float_literal(*f)),
            Expr::StringLiteral(s, _) => format!("Value(std::string({}))", cpp_string_literal(s)),
            Expr::BoolLiteral(b, _) => format!("Value({})", b),
            Expr::NullLiteral(_) => "Value()".to_string(),
            Expr::ArrayLiteral(elems, _) => {
                let items = elems.iter().map(|el| self.emit_expr(el)).collect::<Vec<_>>().join(", ");
                format!("pv::make_array({{{}}})", items)
            }
            Expr::Ident(name, span) => {
                // A bare top-level function name used where a value is
                // expected. C++ would silently convert the function pointer
                // to `bool` via Value(bool) and hand the runtime `true` --
                // no error, just wrong behaviour that is very hard to trace
                // back. The only position where a function name is
                // meaningful is a callback argument, and that path never
                // reaches emit_expr (see emit_callback_call).
                if self.top_level_fns.contains_key(name) {
                    self.errors.push(CodegenDiagnostic {
                        message: format!(
                            "`{}` is a function, and PlainVulkan values can't hold a function. \
                             Did you mean to call it -- `{}(...)`? (Passing a function by name \
                             is only supported for the network callback commands: {}.)",
                            name,
                            name,
                            CALLBACK_COMMANDS
                                .iter()
                                .map(|(n, _)| format!("Pv::{}", n))
                                .collect::<Vec<_>>()
                                .join(", ")
                        ),
                        span: Some(*span),
                    });
                }
                sanitize_ident(name)
            }
            Expr::Index(base, idx, _) => {
                format!("pv::index_get({}, {})", self.emit_expr(base), self.emit_expr(idx))
            }
            Expr::Member(base, field, _) => {
                format!("pv::member_get({}, {})", self.emit_expr(base), cpp_string_literal(field))
            }
            Expr::Scope(_base, name, span) => {
                self.warnings.push(CodegenDiagnostic {
                    message: format!(
                        "`{}` is referenced without being called; PlainVulkan's runtime values \
                         can't hold a bare engine-function reference, so this becomes `null`. \
                         Did you mean to call it, e.g. `Pv::{}(...)`?",
                        name, name
                    ),
                    span: Some(*span),
                });
                "Value()".to_string()
            }
            Expr::Call(callee, args, span) => self.emit_call(callee, args, *span),
            Expr::Unary(op, operand, _) => {
                let o = self.emit_expr(operand);
                match op {
                    UnaryOp::Neg => format!("(-{})", o),
                    UnaryOp::Not => format!("(!{})", o),
                    UnaryOp::BitNot => format!("(~{})", o),
                }
            }
            Expr::Binary(op, l, r, _) => {
                let lc = self.emit_expr(l);
                let rc = self.emit_expr(r);
                match op {
                    BinaryOp::Add => format!("({} + {})", lc, rc),
                    BinaryOp::Sub => format!("({} - {})", lc, rc),
                    BinaryOp::Mul => format!("({} * {})", lc, rc),
                    BinaryOp::Div => format!("({} / {})", lc, rc),
                    BinaryOp::Mod => format!("({} % {})", lc, rc),
                    BinaryOp::Eq => format!("({} == {})", lc, rc),
                    BinaryOp::Ne => format!("({} != {})", lc, rc),
                    BinaryOp::Lt => format!("({} < {})", lc, rc),
                    BinaryOp::Gt => format!("({} > {})", lc, rc),
                    BinaryOp::Le => format!("({} <= {})", lc, rc),
                    BinaryOp::Ge => format!("({} >= {})", lc, rc),
                    // Short-circuiting: see the note on Value's missing
                    // operator&&/|| in pv_value.h.
                    BinaryOp::And => format!("Value((bool)({}) && (bool)({}))", lc, rc),
                    BinaryOp::Or => format!("Value((bool)({}) || (bool)({}))", lc, rc),
                }
            }
            Expr::Ternary(c, t, f, _) => format!(
                "((bool)({}) ? ({}) : ({}))",
                self.emit_expr(c),
                self.emit_expr(t),
                self.emit_expr(f)
            ),
            Expr::Assign(target, op, value, _) => {
                let value_cpp = self.emit_expr(value);
                if self.is_const(self.root_ident(target)) {
                    self.errors.push(CodegenDiagnostic {
                        message: format!(
                            "cannot assign to `{}`: it was declared `const`",
                            self.root_ident(target)
                        ),
                        span: Some(e.span()),
                    });
                }
                self.emit_assign_as_expr(target, *op, value_cpp)
            }
        }
    }

    /// Emits one of the four network callback commands. Their runtime
    /// signature takes a raw `Value(*)(...)` function pointer, so the only
    /// thing that can legally be passed is the name of a *top-level*
    /// `function` with the right parameter count. Everything else is
    /// rejected here with a source-level message rather than being handed
    /// to the C++ compiler, which would report it as an unreadable
    /// "cannot convert 'pv::Value' to 'pv::rt::NetCallback1'" against
    /// generated code the user never wrote.
    fn emit_callback_call(
        &mut self,
        name: &str,
        cb_arity: usize,
        args: &[Expr],
        span: Span,
    ) -> String {
        if args.len() != 1 {
            self.errors.push(CodegenDiagnostic {
                message: format!("Pv::{} expects 1 argument (a callback function), got {}", name, args.len()),
                span: Some(span),
            });
            return "Value()".to_string();
        }
        let arg_name = match &args[0] {
            Expr::Ident(n, _) => n.clone(),
            _ => {
                self.errors.push(CodegenDiagnostic {
                    message: format!(
                        "Pv::{} takes a callback *function*, so its argument must be the name \
                         of a top-level `function` -- not an expression or literal. Write \
                         `function MyHandler({}) {{ ... }}` and pass `Pv::{}(MyHandler);`",
                        name,
                        if cb_arity == 1 { "arg" } else { "" },
                        name
                    ),
                    span: Some(span),
                });
                return "Value()".to_string();
            }
        };
        match self.top_level_fns.get(&arg_name) {
            None => {
                self.errors.push(CodegenDiagnostic {
                    message: format!(
                        "Pv::{} takes a callback function, but `{}` is not a top-level \
                         `function` in this file. (A variable can't hold a function, and a \
                         function nested inside a block compiles to a closure, which the \
                         engine's callback slot cannot store -- declare `{}` at the top level.)",
                        name, arg_name, arg_name
                    ),
                    span: Some(span),
                });
                return "Value()".to_string();
            }
            Some(&declared) if declared != cb_arity => {
                self.errors.push(CodegenDiagnostic {
                    message: format!(
                        "Pv::{} calls its callback with {} argument(s), but `{}` declares {}. \
                         Change `{}` to take exactly {} parameter(s).",
                        name, cb_arity, arg_name, declared, arg_name, cb_arity
                    ),
                    span: Some(span),
                });
                return "Value()".to_string();
            }
            Some(_) => {}
        }
        format!("pv::rt::{}({})", name, sanitize_ident(&arg_name))
    }

    fn emit_call(&mut self, callee: &Expr, args: &[Expr], span: Span) -> String {
        if let Expr::Scope(base, name, _) = callee {
            if let Expr::Ident(ns, _) = base.as_ref() {
                // Callback commands take a function pointer, so their
                // argument must NOT go through emit_expr (which would wrap
                // it in a Value). Validate and emit the bare name instead.
                if ns == "Pv" {
                    if let Some(cb_arity) = callback_arity(name) {
                        return self.emit_callback_call(name, cb_arity, args, span);
                    }
                }
                let args_cpp: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                if ns == "Pv" {
                    match pv_commands::lookup(name) {
                        Some(sig) if sig.arity != args.len() => {
                            self.errors.push(CodegenDiagnostic {
                                message: format!(
                                    "Pv::{} expects {} argument(s), got {}",
                                    name,
                                    sig.arity,
                                    args.len()
                                ),
                                span: Some(span),
                            });
                        }
                        Some(_) => {}
                        None => {
                            self.warnings.push(CodegenDiagnostic {
                                message: format!(
                                    "Pv::{} is not a recognized engine command (typo, or a \
                                     newer runtime function this compiler doesn't know about \
                                     yet); emitting the call and letting the linker decide",
                                    name
                                ),
                                span: Some(span),
                            });
                        }
                    }
                    return format!("pv::rt::{}({})", name, args_cpp.join(", "));
                }
                // Any other namespace is emitted as a literal C++ scoped
                // call. This is an intentional extension point: a user who
                // wants `MyLib::Thing(...)` just needs to provide a
                // matching `namespace MyLib { Value Thing(...); }` in a
                // header they add to the runtime's include path.
                return format!("{}::{}({})", ns, name, args_cpp.join(", "));
            }
        }
        if let Expr::Ident(name, _) = callee {
            let args_cpp: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
            return format!("{}({})", sanitize_ident(name), args_cpp.join(", "));
        }
        self.errors.push(CodegenDiagnostic {
            message: "calling a non-identifier, non-`Namespace::Function` expression isn't \
                       supported by the code generator (PlainVulkan values can't hold callable \
                       closures, so e.g. `arr[0]()` has no runtime representation to call)"
                .to_string(),
            span: Some(span),
        });
        "Value()".to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate C++ for a .pv source, expecting success.
    fn gen_ok(src: &str) -> String {
        let program = pv_transpiler::parse(src).expect("source should parse");
        match generate(&program) {
            Ok(out) => out.cpp,
            Err(errs) => panic!(
                "expected codegen to succeed, got: {:?}",
                errs.iter().map(|e| &e.message).collect::<Vec<_>>()
            ),
        }
    }

    /// Generate C++ for a .pv source, expecting a codegen error whose text
    /// contains `needle`.
    fn gen_err(src: &str, needle: &str) {
        let program = pv_transpiler::parse(src).expect("source should parse");
        match generate(&program) {
            Ok(_) => panic!("expected a codegen error mentioning {:?}, but generation succeeded", needle),
            Err(errs) => {
                let joined = errs.iter().map(|e| e.message.clone()).collect::<Vec<_>>().join("\n");
                assert!(
                    joined.contains(needle),
                    "expected an error mentioning {:?}, got:\n{}",
                    needle,
                    joined
                );
            }
        }
    }

    // ---- top-level `return` -------------------------------------------
    // main() returns int, so a top-level `return` must not emit
    // `return Value(...)`. That produced C++ that did not compile at all.

    #[test]
    fn top_level_return_with_value_is_an_int_exit_code() {
        let cpp = gen_ok("Pv::Init();\nreturn 2;\n");
        assert!(!cpp.contains("return Value(static_cast<int64_t>(2));"),
                "must not return a Value from main:\n{}", cpp);
        assert!(cpp.contains("static_cast<int>(__ret.asInt())"),
                "expected an int exit-code return:\n{}", cpp);
    }

    #[test]
    fn top_level_bare_return_returns_zero() {
        let cpp = gen_ok("Pv::Init();\nreturn;\n");
        assert!(cpp.contains("return 0;"), "expected `return 0;`:\n{}", cpp);
        assert!(!cpp.contains("return Value();"), "must not return a Value from main:\n{}", cpp);
    }

    #[test]
    fn top_level_return_inside_a_nested_block_still_returns_int() {
        let cpp = gen_ok("Pv::Init();\nif (true) { return 1; }\n");
        assert!(cpp.contains("static_cast<int>(__ret.asInt())"),
                "a return nested in a block at top level is still main's return:\n{}", cpp);
    }

    #[test]
    fn return_inside_a_function_still_returns_a_value() {
        let cpp = gen_ok("function F() { return 5; }\nPv::Init();\n");
        assert!(cpp.contains("return Value(static_cast<int64_t>(5));"),
                "function returns stay Value-typed:\n{}", cpp);
    }

    #[test]
    fn return_inside_a_nested_function_still_returns_a_value() {
        let cpp = gen_ok("Pv::Init();\n{ function G() { return 7; } }\n");
        assert!(cpp.contains("return Value(static_cast<int64_t>(7));"),
                "nested-function returns stay Value-typed:\n{}", cpp);
    }

    // ---- main() exception guard ---------------------------------------

    #[test]
    fn main_body_is_wrapped_in_an_exception_guard() {
        let cpp = gen_ok("Pv::Init();\n");
        assert!(cpp.contains("try {"), "main should open a try block:\n{}", cpp);
        assert!(cpp.contains("catch (const std::exception& e)"), "expected a std::exception handler:\n{}", cpp);
        assert!(cpp.contains("catch (...)"), "expected a catch-all handler:\n{}", cpp);
    }

    // ---- network callback commands ------------------------------------
    // These take a C++ function pointer, not a Value, so their argument has
    // to be a top-level function of matching arity. Anything else used to
    // reach the C++ compiler as an unreadable conversion error.

    #[test]
    fn callback_accepts_a_matching_top_level_function() {
        let cpp = gen_ok("function OnMsg(d) { Pv::Log(d); }\nPv::OnReceive(OnMsg);\n");
        assert!(cpp.contains("pv::rt::OnReceive(u_OnMsg)"),
                "callback should be passed as a bare function name:\n{}", cpp);
        assert!(!cpp.contains("pv::rt::OnReceive(Value"),
                "callback argument must not be wrapped in a Value:\n{}", cpp);
    }

    #[test]
    fn zero_arg_callback_accepts_a_zero_arg_function() {
        let cpp = gen_ok("function Up() { Pv::Log(1); }\nPv::OnConnect(Up);\n");
        assert!(cpp.contains("pv::rt::OnConnect(u_Up)"), "{}", cpp);
    }

    #[test]
    fn callback_rejects_a_literal() {
        gen_err("Pv::OnConnect(1);\n", "must be the name of a top-level `function`");
    }

    #[test]
    fn callback_rejects_an_expression() {
        gen_err("var x = 1;\nPv::OnConnect(x + 1);\n", "must be the name of a top-level `function`");
    }

    #[test]
    fn callback_rejects_an_undeclared_name() {
        gen_err("Pv::OnReceive(NoSuchFn);\n", "is not a top-level `function`");
    }

    #[test]
    fn callback_rejects_a_variable() {
        gen_err("var handler = 1;\nPv::OnReceive(handler);\n", "is not a top-level `function`");
    }

    #[test]
    fn callback_rejects_a_nested_function() {
        // A nested function compiles to a std::function closure, which does
        // not convert to a raw function pointer.
        gen_err(
            "{ function Inner(d) { Pv::Log(d); } }\nPv::OnReceive(Inner);\n",
            "is not a top-level `function`",
        );
    }

    #[test]
    fn callback_rejects_wrong_parameter_count() {
        gen_err("function H() { Pv::Log(1); }\nPv::OnReceive(H);\n", "declares 0");
    }

    #[test]
    fn callback_rejects_wrong_parameter_count_the_other_way() {
        gen_err("function H(a) { Pv::Log(a); }\nPv::OnConnect(H);\n", "declares 1");
    }

    // ---- functions used as values --------------------------------------
    // A function pointer converts implicitly to bool, so this used to
    // compile and silently pass `true` to the runtime.

    #[test]
    fn function_used_as_a_value_is_rejected() {
        gen_err("function Helper() { Pv::Log(1); }\nPv::Log(Helper);\n", "can't hold a function");
    }

    #[test]
    fn function_assigned_to_a_variable_is_rejected() {
        gen_err("function Helper() { Pv::Log(1); }\nvar f = Helper;\n", "can't hold a function");
    }

    #[test]
    fn calling_a_function_normally_still_works() {
        let cpp = gen_ok("function Helper() { Pv::Log(1); }\nPv::Log(Helper());\n");
        assert!(cpp.contains("u_Helper()"), "a normal call is unaffected:\n{}", cpp);
    }

    // ---- things that must keep working ---------------------------------

    #[test]
    fn arity_mismatch_on_a_normal_command_is_still_caught() {
        gen_err("Pv::CreateWindow(1);\n", "expects 3 argument(s), got 1");
    }

    #[test]
    fn for_loop_emits_a_real_for_so_continue_runs_the_update() {
        let cpp = gen_ok("for (var i = 0; i < 3; i += 1) { continue; }\n");
        assert!(cpp.contains("for ("), "for must compile to a C++ for loop:\n{}", cpp);
    }
}
