//! Every `Pv::` engine command from the language reference, paired with its
//! expected argument count. `codegen.rs` checks each `Pv::Foo(...)` call
//! site against this table before emitting C++, so a wrong argument count
//! is caught as a precise `pvcc` diagnostic instead of a much less
//! readable C++ compiler error two build stages later.
//!
//! This list is intentionally exhaustive (it mirrors `runtime/include/pv/
//! pv_runtime.h` function-for-function) rather than derived automatically,
//! since PlainVulkan's grammar treats `Namespace::name(...)` fully
//! generically (see pv.lalrpop) -- nothing forces the two lists to match
//! syntactically, so `runtime/README.md` documents keeping them in sync
//! whenever a command is added.

pub struct CommandSig {
    pub name: &'static str,
    pub arity: usize,
}

macro_rules! sig {
    ($name:literal, $arity:literal) => {
        CommandSig { name: $name, arity: $arity }
    };
}

pub const PV_COMMANDS: &[CommandSig] = &[
    // Core / Window
    sig!("Init", 0),
    sig!("Shutdown", 0),
    sig!("CreateWindow", 3),
    sig!("CloseWindow", 0),
    sig!("SetWindowTitle", 1),
    sig!("SetWindowSize", 2),
    sig!("IsWindowOpen", 0),
    sig!("SetVSync", 1),
    sig!("SetFullscreen", 1),
    // Frame / Time
    sig!("BeginFrame", 0),
    sig!("EndFrame", 0),
    sig!("Clear", 1),
    sig!("SetClearColor", 4),
    sig!("GetDeltaTime", 0),
    sig!("GetFPS", 0),
    // Camera
    sig!("SetCamera", 3),
    sig!("LookAt", 3),
    sig!("SetFOV", 1),
    sig!("SetNearFar", 2),
    sig!("SetOrthographic", 1),
    sig!("MoveCamera", 3),
    sig!("RotateCamera", 3),
    // 2D Drawing
    sig!("DrawTriangle", 3),
    sig!("DrawRect", 5),
    sig!("DrawCircle", 4),
    sig!("DrawLine", 5),
    sig!("DrawSprite", 3),
    sig!("DrawSpriteEx", 5),
    sig!("DrawText", 4),
    sig!("DrawTextEx", 6),
    // 3D Drawing
    sig!("DrawMesh", 4),
    sig!("DrawMeshEx", 8),
    sig!("DrawSkybox", 1),
    sig!("DrawTerrain", 2),
    sig!("DrawBillboard", 6),
    sig!("SetWireframe", 1),
    // Mesh management
    sig!("LoadMesh", 1),
    sig!("UnloadMesh", 1),
    sig!("CreateMesh", 2),
    sig!("UpdateMesh", 2),
    sig!("CreateCube", 1),
    sig!("CreateSphere", 2),
    sig!("CreatePlane", 2),
    sig!("CreateCylinder", 2),
    // Textures
    sig!("LoadTexture", 1),
    sig!("UnloadTexture", 1),
    sig!("CreateTexture", 3),
    sig!("SetTextureFilter", 2),
    sig!("SetTextureWrap", 2),
    sig!("LoadCubemap", 1),
    sig!("CreateRenderTexture", 2),
    // Shaders
    sig!("LoadShader", 2),
    sig!("UnloadShader", 1),
    sig!("SetShader", 1),
    sig!("ResetShader", 0),
    sig!("SetUniformInt", 3),
    sig!("SetUniformFloat", 3),
    sig!("SetUniformVec2", 4),
    sig!("SetUniformVec3", 5),
    sig!("SetUniformVec4", 6),
    sig!("SetUniformMat4", 3),
    sig!("SetUniformTexture", 4),
    // Lighting
    sig!("SetAmbient", 4),
    sig!("AddPointLight", 8),
    sig!("AddDirectionalLight", 7),
    sig!("AddSpotLight", 8),
    sig!("RemoveLight", 1),
    sig!("SetShadows", 1),
    sig!("SetShadowResolution", 1),
    sig!("SetFog", 5),
    // Materials
    sig!("CreateMaterial", 0),
    sig!("SetMaterialAlbedo", 2),
    sig!("SetMaterialNormal", 2),
    sig!("SetMaterialRoughness", 2),
    sig!("SetMaterialMetallic", 2),
    sig!("SetMaterialEmissive", 3),
    sig!("SetMaterialColor", 5),
    sig!("SetMaterialHeight", 3),
    // Audio
    sig!("LoadSound", 1),
    sig!("UnloadSound", 1),
    sig!("PlaySound", 1),
    sig!("StopSound", 1),
    sig!("PauseSound", 1),
    sig!("SetSoundVolume", 2),
    sig!("SetSoundPitch", 2),
    sig!("LoadMusic", 1),
    sig!("PlayMusic", 1),
    sig!("StopMusic", 1),
    sig!("SetMusicVolume", 2),
    sig!("SetSound3D", 4),
    // Input: keyboard
    sig!("IsKeyDown", 1),
    sig!("IsKeyUp", 1),
    sig!("IsKeyPressed", 1),
    sig!("IsKeyReleased", 1),
    sig!("GetKeyPressed", 0),
    // Input: mouse
    sig!("GetMouseX", 0),
    sig!("GetMouseY", 0),
    sig!("GetMouseDeltaX", 0),
    sig!("GetMouseDeltaY", 0),
    sig!("IsMouseDown", 1),
    sig!("IsMousePressed", 1),
    sig!("IsMouseReleased", 1),
    sig!("GetMouseScroll", 0),
    sig!("SetMouseVisible", 1),
    sig!("SetMouseLocked", 1),
    sig!("SetMousePosition", 2),
    // Input: gamepad
    sig!("IsGamepadConnected", 1),
    sig!("IsGamepadButtonDown", 2),
    sig!("IsGamepadButtonPressed", 2),
    sig!("GetGamepadAxis", 2),
    sig!("SetGamepadVibration", 3),
    // Physics
    sig!("InitPhysics", 0),
    sig!("SetGravity", 3),
    sig!("StepPhysics", 1),
    sig!("CreateBoxCollider", 6),
    sig!("CreateSphereCollider", 4),
    sig!("CreateCapsuleCollider", 5),
    sig!("CreateRigidBody", 2),
    sig!("SetBodyVelocity", 4),
    sig!("GetBodyVelocity", 1),
    sig!("AddForce", 4),
    sig!("AddImpulse", 4),
    sig!("Raycast", 7),
    // File system
    sig!("FileExists", 1),
    sig!("ReadFile", 1),
    sig!("WriteFile", 2),
    sig!("DeleteFile", 1),
    sig!("GetWorkingDir", 0),
    sig!("SetWorkingDir", 1),
    // UI
    sig!("BeginUI", 0),
    sig!("EndUI", 0),
    sig!("UIButton", 5),
    sig!("UIText", 5),
    sig!("UIImage", 5),
    sig!("UISlider", 6),
    sig!("UICheckbox", 4),
    sig!("UIInputText", 4),
    sig!("UIProgressBar", 5),
    // Debug
    sig!("DrawDebugLine", 7),
    sig!("DrawDebugBox", 7),
    sig!("DrawDebugSphere", 5),
    sig!("Log", 1),
    sig!("LogWarning", 1),
    sig!("LogError", 1),
    sig!("Assert", 2),
    // Animation
    sig!("LoadAnimation", 1),
    sig!("UnloadAnimation", 1),
    sig!("PlayAnimation", 2),
    sig!("PauseAnimation", 1),
    sig!("StopAnimation", 1),
    sig!("SetAnimationSpeed", 2),
    sig!("SetAnimationLoop", 2),
    sig!("IsAnimationPlaying", 1),
    sig!("GetAnimationTime", 1),
    sig!("SetAnimationTime", 2),
    sig!("GetAnimationDuration", 1),
    sig!("BlendAnimation", 3),
    sig!("UpdateAnimations", 1),
    // Physics: new with the PhysX backend
    sig!("GetBodyPosition", 1),
    sig!("SetBodyPosition", 4),
    sig!("GetBodyRotation", 1),
    sig!("SetBodyRotation", 4),
    sig!("AddTorque", 4),
    sig!("SetBodyAngularVelocity", 4),
    sig!("GetBodyAngularVelocity", 1),
    sig!("SetBodyKinematic", 2),
    sig!("SetBodyDamping", 3),
    sig!("SetBodyGravityEnabled", 2),
    sig!("SetBodyFreezePosition", 4),
    sig!("SetBodyFreezeRotation", 4),
    sig!("SetColliderMaterial", 4),
    sig!("SetColliderTrigger", 2),
    sig!("DestroyBody", 1),
    sig!("SetPhysicsTimestep", 2),
    sig!("GetContacts", 0),
    sig!("GetPhysicsBackend", 0),
    // Particles
    sig!("CreateEmitter", 3),
    sig!("DestroyEmitter", 1),
    sig!("SetEmitterPosition", 4),
    sig!("SetEmitterRotation", 4),
    sig!("SetEmitterShape", 4),
    sig!("SetEmitterRate", 2),
    sig!("SetEmitterLifetime", 3),
    sig!("SetEmitterSpeed", 3),
    sig!("SetEmitterSize", 3),
    sig!("SetEmitterColor", 3),
    sig!("SetEmitterGravity", 4),
    sig!("SetEmitterDrag", 2),
    sig!("SetEmitterTexture", 2),
    sig!("SetEmitterBlend", 2),
    sig!("SetEmitterMaxParticles", 2),
    sig!("SetEmitterLocalSpace", 2),
    sig!("SetEmitterEnabled", 2),
    sig!("BurstParticles", 2),
    sig!("ClearParticles", 1),
    sig!("GetParticleCount", 1),
    sig!("UpdateParticles", 1),
    sig!("DrawEmitter", 1),
    sig!("DrawParticles", 0),
    // Animation: new
    sig!("CrossFadeAnimation", 3),
    sig!("GetAnimationClipCount", 1),
    sig!("GetAnimationClipName", 2),
    sig!("GetAnimationTransform", 1),
    sig!("CreateAnimation", 0),
    sig!("AddAnimationClip", 2),
    sig!("AddAnimationKey", 7),
    // Scene
    sig!("NewScene", 1),
    sig!("LoadScene", 1),
    sig!("SaveScene", 1),
    sig!("StartScene", 0),
    sig!("StopScene", 0),
    sig!("UpdateScene", 1),
    sig!("DrawScene", 0),
    sig!("CreateEntity", 1),
    sig!("CreateChildEntity", 2),
    sig!("DestroyEntity", 1),
    sig!("FindEntity", 1),
    sig!("FindEntitiesByTag", 1),
    sig!("SetEntityParent", 2),
    sig!("SetEntityPosition", 4),
    sig!("GetEntityPosition", 1),
    sig!("SetEntityRotation", 4),
    sig!("GetEntityRotation", 1),
    sig!("SetEntityScale", 4),
    sig!("SetEntityActive", 2),
    sig!("AddEntityTag", 2),
    sig!("SetEntityMesh", 2),
    sig!("SetEntityMaterial", 2),
    sig!("AddEntityLight", 6),
    sig!("AddEntityBody", 6),
    sig!("AddEntityEmitter", 1),
    sig!("GetEntityEmitter", 1),
    sig!("AddEntityAnimator", 3),
    sig!("GetEntityAnimation", 1),
    sig!("AddEntityCamera", 2),
    sig!("SetActiveCamera", 1),
    sig!("GetEntityBody", 1),
    sig!("GetEntityCount", 0),
    // Networking: connection management
    sig!("Connect", 2),
    sig!("Disconnect", 0),
    sig!("IsConnected", 0),
    sig!("GetConnectionStatus", 0),
    sig!("GetConnectionError", 0),
    sig!("GetSessionToken", 0),
    // Networking: sending
    sig!("Send", 1),
    sig!("SendRaw", 1),
    sig!("Flush", 0),
    // Networking: receiving
    sig!("Receive", 0),
    sig!("ReceiveNonBlocking", 0),
    sig!("ReceiveTimeout", 1),
    sig!("PollMessages", 0),
    sig!("ClearMessageQueue", 0),
    // Networking: input serialization helpers
    sig!("SerializeInput", 4),
    sig!("SerializePlayerState", 1),
    sig!("DeserializeState", 1),
    sig!("DeserializePlayerPosition", 2),
    // Networking: callbacks
    sig!("OnConnect", 1),
    sig!("OnDisconnect", 1),
    sig!("OnReceive", 1),
    sig!("OnNetworkError", 1),
    // Networking: latency & debugging
    sig!("GetLatency", 0),
    sig!("GetPacketLoss", 0),
    sig!("GetBytesReceived", 0),
    sig!("GetBytesSent", 0),
    sig!("EnableNetworkDebug", 1),
    sig!("GetNetworkStats", 0),
    // Networking: peer-to-peer
    sig!("Listen", 1),
    sig!("AcceptConnection", 0),
    sig!("SendToPeer", 2),
    sig!("ReceiveFromPeer", 0),
    // Terrain
    sig!("CreateTerrain", 3),
    sig!("GenerateTerrain", 4),
    sig!("LoadTerrainHeightmap", 2),
    sig!("DestroyTerrain", 1),
    sig!("SetTerrainOrigin", 4),
    sig!("SetTerrainHeight", 4),
    sig!("GetTerrainHeight", 3),
    sig!("GetTerrainNormal", 3),
    sig!("GetTerrainSlope", 3),
    sig!("GetTerrainSize", 1),
    sig!("TerrainRaycast", 8),
    sig!("AddTerrainLayer", 8),
    sig!("SetTerrainLayerBlend", 3),
    sig!("ClearTerrainLayers", 1),
    sig!("SampleTerrainLayer", 4),
    sig!("SetTerrainLOD", 3),
    sig!("SetTerrainCollision", 2),
    sig!("GetTerrainStats", 1),
    sig!("BuildTerrainMesh", 1),
    sig!("BakeTerrainTexture", 2),
    sig!("SetTerrainMaterial", 2),
    // AI: navigation grid
    sig!("CreateNavGrid", 5),
    sig!("CreateNavGridFromTerrain", 2),
    sig!("DestroyNavGrid", 1),
    sig!("SetNavCellWalkable", 4),
    sig!("SetNavCellCost", 4),
    sig!("AddNavObstacle", 5),
    sig!("ClearNavObstacles", 1),
    sig!("IsNavPointWalkable", 3),
    sig!("NavLineOfSight", 5),
    sig!("FindPath", 5),
    sig!("FindPathSmoothed", 5),
    sig!("GetNavGridStats", 1),
    // AI: agents
    sig!("CreateAgent", 3),
    sig!("DestroyAgent", 1),
    sig!("SetAgentSpeed", 2),
    sig!("SetAgentTurnRate", 2),
    sig!("SetAgentRadius", 2),
    sig!("SetAgentPosition", 3),
    sig!("SetAgentTarget", 3),
    sig!("StopAgent", 1),
    sig!("UpdateAgents", 1),
    sig!("GetAgentPosition", 1),
    sig!("GetAgentVelocity", 1),
    sig!("GetAgentHeading", 1),
    sig!("HasAgentArrived", 1),
    sig!("GetAgentPath", 1),
    sig!("AgentCanSee", 5),
    sig!("FindNearestAgent", 3),
    sig!("GetAgentCount", 0),
    // AI: state machine and blackboard
    sig!("SetAgentState", 2),
    sig!("GetAgentState", 1),
    sig!("GetAgentStateTime", 1),
    sig!("SetAgentBlackboard", 3),
    sig!("GetAgentBlackboard", 2),
];

pub fn lookup(name: &str) -> Option<&'static CommandSig> {
    PV_COMMANDS.iter().find(|c| c.name == name)
}
